#!/bin/bash -eux


dir=$(echo $0| sed "s;./;_;" | sed "s;.bash;;")


OPTIONh=""
while getopts h OPTION
do
case $OPTION in
h) OPTIONh="TRUE" ;;
esac
done


if [ "$OPTIONh" = "TRUE" ];then
cat "$dir"/help

else

ARGV1=$1
ARGV2=$2

burstexcel()
{


python3 $dir/code.py $ARGV1 $ARGV2

mv tmp-out.xlsx $(echo $ARGV1 | sed "s;.xlsx;;")_$ARGV2.xlsx
}

burstexcel

fi

