#!/bin/bash

# SPDX-FileCopyrightText:2024 hirofumi Murai <murai_h22aa@icloud.com>
# SPDX-License-Identify: MIT

DIR1=$(echo $0|rev|sed "s;/; /;"| awk '{print $2}'| rev)
DIR2=$(echo $0|sed "s;.*/;;"| sed "s;\..*;;" | sed "s;$;/;"| sed "s;^;_;")


while getopts ":h" OPTION
do
	case $OPTION in
		h ) OPTION_h="TRUE";;
	esac
done

if [ "$OPTION_h" = "TRUE" ];then
	cat "${DIR1}${DIR2}"help
else

PASS=$(cat $DIR1$DIR2/conf | shuf -n1)

qpdf --encrypt "$PASS" "$PASS" 40 -- $1 ./$(echo $1| sed "s;.*/;;" |sed "s;.pdf;_encrypted.pdf;")

fi
